#!/bin/bash
echo "GET all todos with no filter"

curl --location --request GET 'http://localhost:4567/todos'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "GET all todos with filter on id = 2"

curl --location --request GET 'http://localhost:4567/todos?id=2'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "GET all todos with filter on title = Wash Dishes"

curl --location --request GET 'http://localhost:4567/todos?title=Wash+Dishes'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "GET all todos with filter on doneStatus = False"

curl --location --request GET 'http://localhost:4567/todos?doneStatus=false'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "GET all todos with filter on doneStatus = True"

curl --location --request GET 'http://localhost:4567/todos?doneStatus=true'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "GET all todos with filter on non-existing id (so id = -1)"

curl --location --request GET 'http://localhost:4567/todos?id=-1'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "HEAD all todos with no filter"

curl --location --head 'http://localhost:4567/todos'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "POST a todo with no request body should give an error"

curl --location --request POST 'http://localhost:4567/todos'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "POST a todo with request body but without the mandatory title field should give an error"

curl --location --request POST 'http://localhost:4567/todos' \
--header 'Content-Type: application/json' \
--data-raw '{
            "doneStatus": true
    	}'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "POST a todo with request body and including the mandatory title field"

curl --location --request POST 'http://localhost:4567/todos' \
--header 'Content-Type: application/json' \
--data-raw '{
	    "title" : "exampleTitle1",
            "doneStatus": true
        }'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "POST a todo with request body but without the mandatory title field and id field"

curl --location --request POST 'http://localhost:4567/todos' \
--header 'Content-Type: application/json' \
--data-raw '{
	    "title" : "exampleTitle1",
	    "id" : "1",
            "doneStatus": true
        }'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "POST a todo with request body with doneStatus as a non boolean input"

curl --location --request POST 'http://localhost:4567/todos' \
--header 'Content-Type: application/json' \
--data-raw '{
            "title" : "exampleTitle1",
            "doneStatus": "string"
        }'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "GET a todo with non-existent id"

curl --location --request GET 'http://localhost:4567/todos/-1'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "GET a todo with existing id"

curl --location --request GET 'http://localhost:4567/todos/2'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "HEAD a todo with existing id"

curl --location --head 'http://localhost:4567/todos/2'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "HEAD a todo with non-existent id (id = -1)"

curl --location --head 'http://localhost:4567/todos/-1'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'

echo "POST a todo with existing id and make doneStatus true instead of False"

curl --location --request POST 'http://localhost:4567/todos/2' \
--header 'Content-Type: application/json' \
--data-raw '{
            "doneStatus": true
        }'

echo $'\n----------------------------------------------------------------------------------------------------------------------------------------------------------------\n'
